export const FR = {
    " - at least {s}s with the configured delay": " - au moins {s} s avec le délai configuré",
    "(click a byte to inspect)": "(cliquez sur un octet pour l'inspecter)",
    "(unnamed)": "(sans nom)",
    "0 = run once. Clicking again stops the periodic send.": "0 = une seule fois. Un nouveau clic arrête l'envoi périodique.",
    "0 disables size rotation": "0 désactive la rotation par taille",
    "0 disables time rotation": "0 désactive la rotation par durée",
    "0 keeps incomplete frames open until the delimiter arrives": "0 garde les trames incomplètes ouvertes jusqu'au délimiteur",
    "0 means unlimited": "0 signifie illimité",
    "1200 bps touch": "Touch 1200 bps",
    "16MB with FFat": "16 Mo avec FFat",
    "8-bit sum of preceding bytes": "Somme 8 bits des octets précédents",
    "8MB with SPIFFS": "8 Mo avec SPIFFS",
    "A new version ({version}) is available. You are using {current}.": "Une nouvelle version ({version}) est disponible. Vous utilisez la {current}.",
    "A new version is available but requires a manual installation (self-signed certificate). Windows will show a security warning: click \"More info\" then \"Run anyway\".": "Une nouvelle version est disponible mais nécessite une installation manuelle (certificat auto-signé). Windows affichera un avertissement : cliquez sur \"Informations complémentaires\" puis \"Exécuter quand même\".",
    "ACK regex": "Regex ACK",
    "ANSI escape sequences": "Séquences d'échappement ANSI",
    "AT command": "Commande AT",
    "AT commands": "Commandes AT",
    "Abandoned": "Abandonné",
    "Abort": "Abandonner",
    "Abort transfer": "Abandonner le transfert",
    "About": "À propos",
    "About DiagTerm": "À propos de DiagTerm",
    "Absolute time": "Heure absolue",
    "Absolute time format": "Format de l'heure absolue",
    "Accent color": "Couleur d'accent",
    "Actions": "Actions",
    "Add": "Ajouter",
    "Add field": "Ajouter un champ",
    "Add filter": "Ajouter un filtre",
    "Add image": "Ajouter une image",
    "Add partition": "Ajouter une partition",
    "Add step": "Ajouter une étape",
    "Advanced": "Avancé",
    "All": "Tout",
    "All files": "Tous les fichiers",
    "All jobs": "Toutes les tâches",
    "All packages": "Tous les paquets",
    "All platforms": "Toutes les plateformes",
    "All ports (or regex, e.g. COM1[0-9])": "Tous les ports (ou regex, ex. COM1[0-9])",
    "Allow developer tools (F12)": "Autoriser les outils de développement (F12)",
    "Also flash boards already connected when starting": "Flasher aussi les cartes déjà branchées au démarrage",
    "Also found in Arduino IDE folder: {v}": "Également présent dans le dossier de l'IDE Arduino : {v}",
    "Also keep the raw partition image": "Conserver aussi l'image brute de la partition",
    "Also use packages installed by the Arduino IDE (Arduino15)": "Utiliser aussi les paquets installés par l'IDE Arduino (Arduino15)",
    "Analyze frame...": "Analyser la trame...",
    "Append checksum": "Ajouter une somme de contrôle",
    "Applies to every board when set (for example 921600)": "S'applique à toutes les cartes si renseigné (par exemple 921600)",
    "Apply to": "Appliquer à",
    "As received": "Tel que reçu",
    "Assert DTR on open": "Activer DTR à l'ouverture",
    "Assert RTS on open": "Activer RTS à l'ouverture",
    "Auto": "Auto",
    "Auto (key:value or CSV)": "Auto (clé:valeur ou CSV)",
    "Auto reply": "Réponse automatique",
    "Auto scale": "Échelle auto",
    "Auto-detect": "Détection auto",
    "Auto-scroll (follow live data)": "Défilement auto (suivre les données en direct)",
    "Automatic": "Automatique",
    "Automatic reconnection": "Reconnexion automatique",
    "Automatic updates off": "Mises à jour automatiques désactivées",
    "Automatic updates on": "Mises à jour automatiques activées",
    "Automatically reconnect lost ports": "Reconnecter automatiquement les ports perdus",
    "Automation": "Automatisation",
    "Background": "Arrière-plan",
    "Backup": "Sauvegarde",
    "Baud rate": "Débit (bauds)",
    "Binary": "Binaire",
    "Binary file": "Fichier binaire",
    "Binary image": "Image binaire",
    "Board": "Carte",
    "Board already in BOOTSEL mode": "Carte déjà en mode BOOTSEL",
    "Board default": "Défaut de la carte",
    "Board manager": "Gestionnaire de cartes",
    "Board manager URLs": "URL du gestionnaire de cartes",
    "Board manager...": "Gestionnaire de cartes...",
    "Board package {key} updated from {from} to {to}": "Paquet de cartes {key} mis à jour de {from} vers {to}",
    "Board packages are up to date": "Les paquets de cartes sont à jour",
    "Board scheme": "Schéma de la carte",
    "Boards flashed in parallel": "Cartes flashées en parallèle",
    "Bold": "Gras",
    "Both": "Les deux",
    "Break": "Break",
    "Bridge started: {d}": "Pont démarré : {d}",
    "Bridges": "Ponts",
    "Bridges (TCP / WebSocket / COM)...": "Ponts (TCP / WebSocket / COM)...",
    "Bridges and sniffer": "Ponts et sniffer",
    "Browse": "Parcourir",
    "Browse...": "Parcourir...",
    "Build filesystem": "Construire le système de fichiers",
    "Build folder": "Dossier de build",
    "Build folder exported from the Arduino IDE / PlatformIO / ESP-IDF": "Dossier de build exporté depuis l'IDE Arduino / PlatformIO / ESP-IDF",
    "Build image only...": "Construire l'image uniquement...",
    "Building filesystem image": "Construction de l'image du système de fichiers",
    "Built with Electron": "Construit avec Electron",
    "Burn bootloader": "Graver le bootloader",
    "Burn the bootloader on {n} board(s)? Fuses will be written.": "Graver le bootloader sur {n} carte(s) ? Les fusibles seront écrits.",
    "Burning bootloader": "Gravure du bootloader",
    "Byte at": "Octet à",
    "Bytes": "Octets",
    "Bytes >= 0x80": "Octets >= 0x80",
    "COM to COM sniffer (man in the middle)": "Sniffer COM vers COM (homme du milieu)",
    "COMNEX command failed: {error}": "Échec de la commande COMNEX : {error}",
    "COMNEX hubs": "Hubs COMNEX",
    "COMNEX level shifter": "Adaptateur de niveau COMNEX",
    "COMNEX level shifter set to {v}": "Adaptateur de niveau COMNEX réglé sur {v}",
    "CRC-16/CCITT-FALSE of preceding bytes (BE)": "CRC-16/CCITT-FALSE des octets précédents (BE)",
    "CRC-16/MODBUS of preceding bytes (LE)": "CRC-16/MODBUS des octets précédents (LE)",
    "CRC-16/XMODEM of preceding bytes (BE)": "CRC-16/XMODEM des octets précédents (BE)",
    "CRC-32 of preceding bytes (LE)": "CRC-32 des octets précédents (LE)",
    "CRC-8 of preceding bytes": "CRC-8 des octets précédents",
    "Cancel": "Annuler",
    "Cancel all": "Tout annuler",
    "Cancelled": "Annulé",
    "Capture saved: {file}": "Capture enregistrée : {file}",
    "Capture span": "Durée de la capture",
    "Case sensitive": "Sensible à la casse",
    "Change board": "Changer de carte",
    "Channel {n}": "Canal {n}",
    "Check board updates now": "Vérifier les mises à jour des cartes",
    "Check for DiagTerm updates on startup": "Rechercher les mises à jour de DiagTerm au démarrage",
    "Check for updates": "Rechercher des mises à jour",
    "Checking board packages...": "Vérification des paquets de cartes...",
    "Checking for updates...": "Recherche de mises à jour...",
    "Checksum (trailing)": "Somme de contrôle (en fin)",
    "Checksum candidates": "Sommes de contrôle possibles",
    "Checksum finder": "Recherche de somme de contrôle",
    "Checksum skipping the first N bytes": "Somme de contrôle en ignorant les N premiers octets",
    "Chip": "Puce",
    "Chip info": "Infos puce",
    "Chip information": "Informations sur la puce",
    "Chip model, revision, MAC address, flash size and PSRAM of every selected board.": "Modèle, révision, adresse MAC, taille flash et PSRAM de chaque carte sélectionnée.",
    "Chip tools (info, erase, read flash)": "Outils puce (infos, effacement, lecture flash)",
    "Choose file...": "Choisir un fichier...",
    "Choose reference file (.txt, .log, .json)...": "Choisir le fichier de référence (.txt, .log, .json)...",
    "Choose two different ports": "Choisissez deux ports différents",
    "Chrono start": "Départ chrono",
    "Chrono stop": "Arrêt chrono",
    "Chronometer": "Chronomètre",
    "Chronometer lap": "Tour du chronomètre",
    "Chronometer reset": "Remise à zéro du chronomètre",
    "Chronometer start / stop": "Démarrer / arrêter le chronomètre",
    "Chronometer: start/stop manually, or from triggers": "Chronomètre : démarrage/arrêt manuel ou par déclencheurs",
    "Chunk size (bytes)": "Taille des blocs (octets)",
    "Clear": "Effacer",
    "Clear (Ctrl+K)": "Effacer (Ctrl+K)",
    "Clear cursors": "Effacer les curseurs",
    "Clear finished": "Effacer les terminées",
    "Clear send history": "Effacer l'historique d'envoi",
    "Clear terminal": "Effacer le terminal",
    "Clear terminal on connect": "Effacer le terminal à la connexion",
    "Click a shortcut to change it, then press the new key combination. Escape cancels, Backspace removes the shortcut. Macros keys (F1-F12) are configured in the macro editor.": "Cliquez sur un raccourci pour le modifier, puis appuyez sur la nouvelle combinaison. Échap annule, Retour arrière supprime le raccourci. Les touches des macros (F1-F12) se configurent dans l'éditeur de macros.",
    "Click a tab to show it here": "Cliquez sur un onglet pour l'afficher ici",
    "Clock time": "Heure",
    "Close": "Fermer",
    "Close other tabs": "Fermer les autres onglets",
    "Close tab": "Fermer l'onglet",
    "Close tab (Ctrl+W)": "Fermer l'onglet (Ctrl+W)",
    "Close {name}? The port will be disconnected.": "Fermer {name} ? Le port sera déconnecté.",
    "Color": "Couleur",
    "Command palette": "Palette de commandes",
    "Compare logs": "Comparer des logs",
    "Compare with a file...": "Comparer avec un fichier...",
    "Compare with a log file": "Comparer avec un fichier de log",
    "Completed": "Terminé",
    "Compressed transfer": "Transfert compressé",
    "Confirm": "Confirmer",
    "Confirm before closing when ports are open or flash jobs are running": "Confirmer avant de fermer si des ports sont ouverts ou des flashs en cours",
    "Conflict": "Conflit",
    "Connect": "Connecter",
    "Connect / disconnect": "Connecter / déconnecter",
    "Connected": "Connecté",
    "Connected since": "Connecté depuis",
    "Connected to {port} at {baud} baud": "Connecté à {port} à {baud} bauds",
    "Connection lost": "Connexion perdue",
    "Connection lost: {reason}": "Connexion perdue : {reason}",
    "Contains": "Contient",
    "Content": "Contenu",
    "Continue": "Continuer",
    "Continue with next frame": "Continuer avec la trame suivante",
    "Control": "Contrôle",
    "Cooldown (ms)": "Délai de réarmement (ms)",
    "Copied {n} bytes as hex": "{n} octets copiés en hexa",
    "Copied {n} rows": "{n} lignes copiées",
    "Copy": "Copier",
    "Copy as C array": "Copier en tableau C",
    "Copy as hex": "Copier en hexa",
    "Copy hex": "Copier l'hexa",
    "Copy text": "Copier le texte",
    "Copy to clipboard": "Copier dans le presse-papiers",
    "Copy with timestamps": "Copier avec horodatage",
    "Create trigger from this frame...": "Créer un déclencheur depuis cette trame...",
    "Current date ({date:YYYY-MM-DD})": "Date courante ({date:YYYY-MM-DD})",
    "Current rate": "Débit actuel",
    "Current time ({time:HH:mm:ss.SSS})": "Heure courante ({time:HH:mm:ss.SSS})",
    "Current view (filters and search)": "Vue actuelle (filtres et recherche)",
    "Custom frame parsers": "Analyseurs de trames personnalisés",
    "Custom frame parsers...": "Analyseurs de trames personnalisés...",
    "Custom images": "Images personnalisées",
    "Custom offset and size": "Offset et taille personnalisés",
    "Cycle timestamp mode": "Changer le mode d'horodatage",
    "DTR on open": "DTR à l'ouverture",
    "Dark": "Sombre",
    "Data": "Données",
    "Data and automation": "Données et automatisation",
    "Data batching interval": "Intervalle de regroupement des données",
    "Data bits": "Bits de données",
    "Data folder (for example the sketch \"data\" folder)": "Dossier de données (par exemple le dossier \"data\" du sketch)",
    "Decode": "Décoder",
    "Decoder": "Décodeur",
    "Decoder values": "Valeurs du décodeur",
    "Default (application data)": "Par défaut (données de l'application)",
    "Default 4MB with FFat": "4 Mo par défaut avec FFat",
    "Default 4MB with SPIFFS": "4 Mo par défaut avec SPIFFS",
    "Default NVS partition of ESP32 Arduino": "Partition NVS par défaut de l'ESP32 Arduino",
    "Default TCP port": "Port TCP par défaut",
    "Default endianness": "Boutisme par défaut",
    "Default height": "Hauteur par défaut",
    "Default line ending": "Fin de ligne par défaut",
    "Default mode": "Mode par défaut",
    "Default send mode": "Mode d'envoi par défaut",
    "Default timestamps": "Horodatage par défaut",
    "Default values applied to new tabs. Each tab can override them.": "Valeurs par défaut appliquées aux nouveaux onglets. Chaque onglet peut les modifier.",
    "Default view": "Vue par défaut",
    "Default visible window": "Fenêtre visible par défaut",
    "Delay (ms)": "Délai (ms)",
    "Delay before": "Délai avant",
    "Delay before reopening": "Délai avant réouverture",
    "Delay between frames (ms)": "Délai entre trames (ms)",
    "Delay between passes (ms)": "Délai entre passes (ms)",
    "Delete": "Supprimer",
    "Delete \"{name}\"?": "Supprimer \"{name}\" ?",
    "Delete profile \"{name}\"?": "Supprimer le profil \"{name}\" ?",
    "Delete workspace \"{name}\"?": "Supprimer l'espace de travail \"{name}\" ?",
    "Delimiter": "Délimiteur",
    "Delimiter (hex)": "Délimiteur (hexa)",
    "Delta (prev. frame)": "Delta (trame préc.)",
    "Destination folder": "Dossier de destination",
    "Detect": "Détecter",
    "Detected patterns": "Motifs détectés",
    "Detected ports": "Ports détectés",
    "Device": "Appareil",
    "Device re-enumerated: {from} -> {to}": "Appareil ré-énuméré : {from} -> {to}",
    "DiagTerm capture (replayable)": "Capture DiagTerm (rejouable)",
    "DiagTerm is a serial terminal, protocol analyzer and multi-board flasher for embedded development.": "DiagTerm est un terminal série, un analyseur de protocoles et un flasheur multi-cartes pour le développement embarqué.",
    "DiagTerm is up to date ({version})": "DiagTerm est à jour ({version})",
    "Direction": "Direction",
    "Directions": "Directions",
    "Disable both DTR and RTS to avoid resetting ESP32/Arduino boards when connecting": "Désactivez DTR et RTS pour éviter de réinitialiser les cartes ESP32/Arduino à la connexion",
    "Disconnect": "Déconnecter",
    "Disconnect port": "Déconnecter le port",
    "Disconnected": "Déconnecté",
    "Disk logging": "Enregistrement sur disque",
    "Disk logging, capture replay, TCP/WebSocket bridges and port sniffer": "Enregistrement sur disque, rejeu de captures, ponts TCP/WebSocket et sniffer de port",
    "Distinct bytes": "Octets distincts",
    "Documents/DiagTerm Logs": "Documents/DiagTerm Logs",
    "Done": "Terminé",
    "Down": "Descendre",
    "Download and extract": "Télécharger et extraire",
    "Download and install": "Télécharger et installer",
    "Download failed: {error}": "Échec du téléchargement : {error}",
    "Download from board": "Télécharger depuis la carte",
    "Download in browser": "Télécharger dans le navigateur",
    "Download opened in your browser. Run the installer once downloaded. If Windows shows a security warning, click \"More info\" then \"Run anyway\".": "Téléchargement ouvert dans votre navigateur. Lancez l'installateur une fois téléchargé. Si Windows affiche un avertissement, cliquez sur \"Informations complémentaires\" puis \"Exécuter quand même\".",
    "Downloading update...": "Téléchargement de la mise à jour...",
    "Drag to resize": "Glisser pour redimensionner",
    "Driver": "Pilote",
    "Dump": "Dump",
    "Duplicate": "Dupliquer",
    "Duplicate settings in a new tab": "Dupliquer les réglages dans un nouvel onglet",
    "Duration": "Durée",
    "Duration on the wire": "Durée sur la ligne",
    "ESP32 standard layout": "Disposition standard ESP32",
    "ESP32, ESP8266, AVR, RP2040, SAMD, STM32, CH55x... from installed packages": "ESP32, ESP8266, AVR, RP2040, SAMD, STM32, CH55x... depuis les paquets installés",
    "Each tab can override this with the Rec button": "Chaque onglet peut le modifier avec le bouton Rec",
    "Edit custom decoders": "Modifier les décodeurs personnalisés",
    "Edit custom frame parsers": "Modifier les analyseurs de trames personnalisés",
    "Edit filters": "Modifier les filtres",
    "Edit highlights": "Modifier les surlignages",
    "Edit macros": "Modifier les macros",
    "Edit triggers": "Modifier les déclencheurs",
    "Edit...": "Modifier...",
    "Empty. Click Add.": "Vide. Cliquez sur Ajouter.",
    "Enable notifications": "Activer les notifications",
    "Enabled": "Activé",
    "Encoding": "Encodage",
    "Encrypted": "Chiffré",
    "End": "Fin",
    "Ending": "Fin",
    "English": "English",
    "Entropy": "Entropie",
    "Epoch (ms)": "Epoch (ms)",
    "Epoch milliseconds": "Millisecondes epoch",
    "Erase": "Effacer",
    "Erase all": "Tout effacer",
    "Erase entire flash first": "Effacer toute la flash avant",
    "Erase flash": "Effacer la flash",
    "Erase region": "Effacer une région",
    "Erase the entire flash of {n} board(s)? This cannot be undone.": "Effacer toute la flash de {n} carte(s) ? Cette action est irréversible.",
    "Erase {size} at {offset} on {n} board(s)?": "Effacer {size} à {offset} sur {n} carte(s) ?",
    "Erases the entire flash memory, including NVS, calibration and filesystem.": "Efface toute la mémoire flash, y compris la NVS, la calibration et le système de fichiers.",
    "Erasing flash": "Effacement de la flash",
    "Erasing region": "Effacement de la région",
    "Error": "Erreur",
    "Errors": "Erreurs",
    "Errors only": "Erreurs uniquement",
    "Escapes (\\n, \\x1B...)": "Échappements (\\n, \\x1B...)",
    "Even": "Paire",
    "Every": "Toutes les",
    "Every board plugged in is flashed automatically with the current configuration.": "Chaque carte branchée est flashée automatiquement avec la configuration actuelle.",
    "Exact": "Exact",
    "Excel CSV (.csv)": "CSV Excel (.csv)",
    "Export": "Exporter",
    "Export (Ctrl+E)": "Exporter (Ctrl+E)",
    "Export CSV": "Exporter en CSV",
    "Export binary": "Exporter en binaire",
    "Export everything...": "Tout exporter...",
    "Export logs": "Exporter les logs",
    "Export or import all settings together with macros, triggers, highlights, decoders, workspaces and flash profiles.": "Exporter ou importer tous les réglages avec les macros, déclencheurs, surlignages, décodeurs, espaces de travail et profils de flash.",
    "Export profiles": "Exporter les profils",
    "Export settings": "Exporter les réglages",
    "Export timeline as PNG": "Exporter la timeline en PNG",
    "Export...": "Exporter...",
    "Exported to {file}": "Exporté vers {file}",
    "Expose a serial port over the network (TCP, Telnet, WebSocket), connect it to a remote TCP server, or insert DiagTerm between two COM ports to sniff both directions.": "Exposer un port série sur le réseau (TCP, Telnet, WebSocket), le connecter à un serveur TCP distant, ou insérer DiagTerm entre deux ports COM pour espionner les deux directions.",
    "Failed": "Échec",
    "Failed to apply settings: {error}": "Impossible d'appliquer les réglages : {error}",
    "Failed to start bridge": "Impossible de démarrer le pont",
    "Failed to start transfer": "Impossible de démarrer le transfert",
    "Fields": "Champs",
    "File": "Fichier",
    "File format": "Format de fichier",
    "File name": "Nom du fichier",
    "File not found": "Fichier introuvable",
    "File sent: {size} in {time}": "Fichier envoyé : {size} en {time}",
    "File transfer": "Transfert de fichier",
    "File transfer failed: {error}": "Échec du transfert de fichier : {error}",
    "Filesystem": "Système de fichiers",
    "Filesystem download": "Téléchargement du système de fichiers",
    "Filesystem image (.bin)": "Image du système de fichiers (.bin)",
    "Filesystem upload": "Envoi du système de fichiers",
    "Filesystem upload and download": "Envoi et téléchargement du système de fichiers",
    "Fill to end": "Remplir jusqu'à la fin",
    "Filter by port, board, serial...": "Filtrer par port, carte, numéro de série...",
    "Filter ports": "Filtrer les ports",
    "Filters: {list}": "Filtres : {list}",
    "Firmware": "Firmware",
    "Firmware file (.bin, .hex, .uf2, .elf)": "Fichier firmware (.bin, .hex, .uf2, .elf)",
    "Fit": "Ajuster",
    "Fit whole capture": "Ajuster à toute la capture",
    "Fix the errors before exporting": "Corrigez les erreurs avant d'exporter",
    "Fix the errors before writing": "Corrigez les erreurs avant d'écrire",
    "Fixed length": "Longueur fixe",
    "Fixed scale": "Échelle fixe",
    "Fixed-size chunks": "Blocs de taille fixe",
    "Flash": "Flash",
    "Flash and boards": "Flash et cartes",
    "Flash boards": "Flasher les cartes",
    "Flash frequency": "Fréquence flash",
    "Flash jobs": "Tâches de flash",
    "Flash mode": "Mode flash",
    "Flash size": "Taille flash",
    "Flash {n} boards": "Flasher {n} cartes",
    "Flash {port}": "Flasher {port}",
    "Flash {r} running, {q} queued": "Flash : {r} en cours, {q} en attente",
    "Flashing": "Flash en cours",
    "Flow control": "Contrôle de flux",
    "Flush idle after (ms)": "Vider après inactivité (ms)",
    "Flush incomplete frame after": "Vider la trame incomplète après",
    "Focus send box": "Aller à la zone d'envoi",
    "Folder (image built automatically)": "Dossier (image construite automatiquement)",
    "Folder whose content becomes the filesystem root": "Dossier dont le contenu devient la racine du système de fichiers",
    "Follow": "Suivre",
    "Follow live data": "Suivre les données en direct",
    "Follow live data by default": "Suivre les données en direct par défaut",
    "Follow system": "Suivre le système",
    "Follow the device by USB serial number when its COM number changes": "Suivre l'appareil par son numéro de série USB quand son numéro COM change",
    "Font family": "Police",
    "Font size": "Taille de police",
    "For hex/ascii/bits": "Pour hex/ascii/bits",
    "Format": "Format",
    "Found": "Trouvé",
    "Four panes": "Quatre volets",
    "Frame": "Trame",
    "Frame #{n} - {dir} - {len} bytes": "Trame n°{n} - {dir} - {len} octets",
    "Frame grouping gap": "Écart de regroupement des trames",
    "Frame length": "Longueur de trame",
    "Frame period": "Période des trames",
    "Frame splitting": "Découpage des trames",
    "Frame splitting (RX)": "Découpage des trames (RX)",
    "Frames": "Trames",
    "Frames split on a delimiter": "Trames découpées sur un délimiteur",
    "Francais": "Français",
    "Free": "Libres",
    "Freeze / resume display": "Figer / reprendre l'affichage",
    "Freeze display": "Figer l'affichage",
    "Freeze display (capture continues)": "Figer l'affichage (la capture continue)",
    "From board": "Depuis la carte",
    "From board options": "Depuis les options de la carte",
    "From folder": "Depuis un dossier",
    "From image file": "Depuis un fichier image",
    "From selected board scheme": "Depuis le schéma de la carte sélectionnée",
    "Gap with previous frame": "Écart avec la trame précédente",
    "General": "Général",
    "Gives the USB driver time to settle after the device reappears": "Laisse au pilote USB le temps de se stabiliser après la réapparition de l'appareil",
    "Go to tab": "Aller à l'onglet",
    "Group": "Groupe",
    "Grow the last partition to the end of the flash": "Étendre la dernière partition jusqu'à la fin de la flash",
    "HH:mm:ss.SSSuuu (microseconds)": "HH:mm:ss.SSSuuu (microsecondes)",
    "HTML table (.html)": "Tableau HTML (.html)",
    "Hardware (RTS/CTS)": "Matériel (RTS/CTS)",
    "Help": "Aide",
    "Hex": "Hexa",
    "Hex bytes": "Octets hexa",
    "Hex bytes, e.g. 01 03 00 00 00 0A {crc16modbus}": "Octets hexa, ex. 01 03 00 00 00 0A {crc16modbus}",
    "Hex dump": "Dump hexa",
    "Hex dump (hex + text)": "Dump hexa (hexa + texte)",
    "Hexadecimal string": "Chaîne hexadécimale",
    "Hidden": "Masqué",
    "High contrast": "Contraste élevé",
    "Highlight frame": "Surligner la trame",
    "Highlight rules": "Règles de surlignage",
    "Highlight rules...": "Règles de surlignage...",
    "Highlight similar frames...": "Surligner les trames similaires...",
    "Host": "Hôte",
    "How often new and removed serial ports are detected": "Fréquence de détection des ports série ajoutés et retirés",
    "How received bytes are grouped into frames in the terminal and timeline": "Comment les octets reçus sont regroupés en trames dans le terminal et la timeline",
    "How to split the file": "Comment découper le fichier",
    "Huge app (3MB, no OTA)": "Grande application (3 Mo, sans OTA)",
    "Identical": "Identiques",
    "Identified from USB IDs:": "Identifiées par les ID USB :",
    "Idle gap (prev. end)": "Inactivité (fin préc.)",
    "Idle timeout": "Délai d'inactivité",
    "If no reply": "Sans réponse",
    "Ignore case": "Ignorer la casse",
    "Ignore numbers": "Ignorer les nombres",
    "Ignore surrounding spaces": "Ignorer les espaces autour",
    "Image build failed": "Échec de la construction de l'image",
    "Image built: {file}": "Image construite : {file}",
    "Import": "Importer",
    "Import CSV...": "Importer un CSV...",
    "Import binary...": "Importer un binaire...",
    "Import complete": "Import terminé",
    "Import profiles": "Importer des profils",
    "Import settings": "Importer des réglages",
    "Import {parts}? Current values will be replaced.": "Importer {parts} ? Les valeurs actuelles seront remplacées.",
    "Import...": "Importer...",
    "Imported {n} items": "{n} éléments importés",
    "In use by flash": "Utilisé par le flash",
    "Incrementing counter ({counter:step:start})": "Compteur incrémental ({counter:step:start})",
    "Indexes updated {date}": "Index mis à jour {date}",
    "Information": "Information",
    "Input": "Saisie",
    "Insert marker": "Insérer un marqueur",
    "Insert marker (Ctrl+M)": "Insérer un marqueur (Ctrl+M)",
    "Insert marker before": "Insérer un marqueur avant",
    "Install": "Installer",
    "Install and restart": "Installer et redémarrer",
    "Install package": "Installer le paquet",
    "Install the packages you need (ESP32, ESP8266, AVR, RP2040, CH55x...) from the board manager. They are downloaded once and kept up to date automatically.": "Installez les paquets nécessaires (ESP32, ESP8266, AVR, RP2040, CH55x...) depuis le gestionnaire de cartes. Ils sont téléchargés une fois puis tenus à jour automatiquement.",
    "Install version": "Installer la version",
    "Installation failed: {error}": "Échec de l'installation : {error}",
    "Installed": "Installé",
    "Intel HEX / Modbus ASCII record": "Enregistrement Intel HEX / Modbus ASCII",
    "Interface scale": "Échelle de l'interface",
    "Interpret escapes like \\n, \\r, \\x1B": "Interpréter les échappements comme \\n, \\r, \\x1B",
    "Invalid JSON export": "Export JSON invalide",
    "Invalid JSON file": "Fichier JSON invalide",
    "Invalid hex input": "Saisie hexa invalide",
    "Invalid number": "Nombre invalide",
    "Invalid offset or size": "Offset ou taille invalide",
    "Invalid pattern": "Motif invalide",
    "Invalid profile file": "Fichier de profil invalide",
    "Invalid workspace file": "Fichier d'espace de travail invalide",
    "JSON-like": "Type JSON",
    "Jobs": "Tâches",
    "Jump to live": "Revenir au direct",
    "Jump to live ({n} new)": "Revenir au direct ({n} nouvelles)",
    "Keep (from image)": "Conserver (depuis l'image)",
    "Keep delimiter": "Conserver le délimiteur",
    "Keep installed board packages up to date automatically": "Tenir à jour automatiquement les paquets de cartes installés",
    "Keep original": "Conserver l'original",
    "Keep previous package versions after an update": "Conserver les versions précédentes après une mise à jour",
    "Keyboard shortcuts": "Raccourcis clavier",
    "LaTeX (.tex)": "LaTeX (.tex)",
    "Label": "Libellé",
    "Language": "Langue",
    "Lap": "Tour",
    "Lap here": "Tour ici",
    "Lap {n}": "Tour {n}",
    "Later": "Plus tard",
    "Layout": "Disposition",
    "Layout: four panes": "Disposition : quatre volets",
    "Layout: single": "Disposition : simple",
    "Layout: two columns": "Disposition : deux colonnes",
    "Layout: two rows": "Disposition : deux lignes",
    "Leave empty to use the theme color": "Laisser vide pour utiliser la couleur du thème",
    "Len": "Long.",
    "Length (bytes)": "Longueur (octets)",
    "Length field": "Champ de longueur",
    "Letters / digits / symbols": "Lettres / chiffres / symboles",
    "Light": "Clair",
    "Line by line (text)": "Ligne par ligne (texte)",
    "Line ending": "Fin de ligne",
    "Line height": "Hauteur de ligne",
    "Line occupancy": "Occupation de la ligne",
    "LittleFS, SPIFFS and FFat filesystem images, partition editor": "Images de systèmes de fichiers LittleFS, SPIFFS et FFat, éditeur de partitions",
    "Live": "Direct",
    "Load": "Charger",
    "Load a preset...": "Charger un préréglage...",
    "Load all": "Tout charger",
    "Load everything instantly with original timestamps, or replay it in real time (with speed control) to watch triggers, plotter and decoders react.": "Tout charger instantanément avec l'horodatage d'origine, ou rejouer en temps réel (avec contrôle de vitesse) pour voir réagir les déclencheurs, le traceur et les décodeurs.",
    "Load instantly": "Charger instantanément",
    "Load without connecting": "Charger sans connecter",
    "Loading a workspace closes the current tabs. Continue?": "Charger un espace de travail ferme les onglets actuels. Continuer ?",
    "Loading...": "Chargement...",
    "Log copied": "Log copié",
    "Log folder": "Dossier des logs",
    "Logic": "Logique",
    "Logic analyzer": "Analyseur logique",
    "Logs": "Logs",
    "Logs are identical": "Les logs sont identiques",
    "Logs too large for a full diff; comparing line by line.": "Logs trop volumineux pour un diff complet ; comparaison ligne par ligne.",
    "Lost": "Perdu",
    "Lost - waiting": "Perdu - en attente",
    "Lower values reduce latency, higher values reduce CPU usage at high baud rates": "Des valeurs faibles réduisent la latence, des valeurs élevées réduisent l'usage CPU à haut débit",
    "Macro \"{name}\": expected response not received at step {n}": "Macro \"{name}\" : réponse attendue non reçue à l'étape {n}",
    "Macros": "Macros",
    "Macros, triggers, file sending with XMODEM/YMODEM and ACK handshake": "Macros, déclencheurs, envoi de fichiers en XMODEM/YMODEM et avec acquittement",
    "Macros...": "Macros...",
    "Macros: save frequent commands, bind F1-F12, sequences and periodic sends.": "Macros : enregistrez vos commandes fréquentes, touches F1-F12, séquences et envois périodiques.",
    "Manufacturer contains": "Fabricant contient",
    "Mark": "Mark",
    "Markdown (.md)": "Markdown (.md)",
    "Marker": "Marqueur",
    "Marker color": "Couleur des marqueurs",
    "Marker label": "Libellé du marqueur",
    "Marker {n}": "Marqueur {n}",
    "Markers": "Marqueurs",
    "Mask": "Masque",
    "Match": "Correspondance",
    "Match case": "Respecter la casse",
    "Matched text": "Texte trouvé",
    "Max frame (bytes)": "Trame max (octets)",
    "Maximize": "Agrandir",
    "Maximum attempts": "Nombre maximal de tentatives",
    "Maximum capture size per tab": "Taille de capture maximale par onglet",
    "Maximum frame length": "Longueur maximale des trames",
    "Maximum frames kept in memory per tab": "Nombre maximal de trames gardées en mémoire par onglet",
    "Measure between selected frames ({d})": "Mesure entre les trames sélectionnées ({d})",
    "Merged image": "Image fusionnée",
    "Minimal SPIFFS (1.9MB app with OTA)": "SPIFFS minimal (application 1,9 Mo avec OTA)",
    "Minimize": "Réduire",
    "Mode": "Mode",
    "Modem input lines": "Lignes d'entrée modem",
    "More": "Plus",
    "Multi-tab, split-view serial terminal with automatic reconnection": "Terminal série multi-onglets, vue partagée et reconnexion automatique",
    "My protocol": "Mon protocole",
    "NAK regex": "Regex NAK",
    "NMEA sentence": "Phrase NMEA",
    "Name": "Nom",
    "Negative = from the end": "Négatif = depuis la fin",
    "New bridge": "Nouveau pont",
    "New macro": "Nouvelle macro",
    "New tab": "Nouvel onglet",
    "New tab (Ctrl+T)": "Nouvel onglet (Ctrl+T)",
    "New terminal": "Nouveau terminal",
    "New terminal tab": "Nouvel onglet terminal",
    "New trigger": "Nouveau déclencheur",
    "Next match": "Occurrence suivante",
    "Next match (Enter)": "Occurrence suivante (Entrée)",
    "Next tab": "Onglet suivant",
    "No COMNEX device found (USB VID 0x1209).": "Aucun appareil COMNEX trouvé (USB VID 0x1209).",
    "No OTA (2MB app, 2MB SPIFFS)": "Sans OTA (application 2 Mo, SPIFFS 2 Mo)",
    "No TX/RX exchanges yet": "Aucun échange TX/RX pour l'instant",
    "No USB filter: every new port is flashed.": "Aucun filtre USB : chaque nouveau port est flashé.",
    "No active bridge": "Aucun pont actif",
    "No active terminal": "Aucun terminal actif",
    "No board matches your search": "Aucune carte ne correspond à votre recherche",
    "No board package installed yet.": "Aucun paquet de cartes installé pour l'instant.",
    "No board selected": "Aucune carte sélectionnée",
    "No data": "Aucune donnée",
    "No file selected": "Aucun fichier sélectionné",
    "No filter: every new port is flashed in production mode": "Aucun filtre : chaque nouveau port est flashé en mode production",
    "No flash job yet. Configure a board and firmware in the Flash tab, select ports and start.": "Aucune tâche de flash. Configurez une carte et un firmware dans l'onglet Flash, sélectionnez les ports et lancez.",
    "No job matches the filter": "Aucune tâche ne correspond au filtre",
    "No known checksum matches the trailing bytes": "Aucune somme de contrôle connue ne correspond aux derniers octets",
    "No laps. Use the lap button, or triggers with a chronometer action.": "Aucun tour. Utilisez le bouton tour, ou des déclencheurs avec une action chronomètre.",
    "No match": "Aucun résultat",
    "No matching command": "Aucune commande correspondante",
    "No package index loaded yet. Click \"Update indexes\".": "Aucun index de paquets chargé. Cliquez sur \"Mettre à jour les index\".",
    "No package matches": "Aucun paquet ne correspond",
    "No port": "Aucun port",
    "No port (BOOTSEL drive / DFU)": "Aucun port (lecteur BOOTSEL / DFU)",
    "No port (programmer over USB)": "Aucun port (programmateur USB)",
    "No programmer for this platform": "Aucun programmateur pour cette plateforme",
    "No protocol recognized. Try the decoder panel or define a custom frame parser.": "Aucun protocole reconnu. Essayez le panneau décodeur ou définissez un analyseur de trames personnalisé.",
    "No saved workspace. A workspace stores every tab with its port, serial settings, view and layout.": "Aucun espace de travail enregistré. Un espace de travail mémorise chaque onglet avec son port, ses réglages série, sa vue et la disposition.",
    "No serial port detected": "Aucun port série détecté",
    "No serial port detected. Plug a device: it will appear here automatically.": "Aucun port série détecté. Branchez un appareil : il apparaîtra ici automatiquement.",
    "No setting matches \"{q}\"": "Aucun réglage ne correspond à \"{q}\"",
    "No time": "Sans heure",
    "None": "Aucun",
    "None (stream)": "Aucun (flux)",
    "Not installed": "Non installé",
    "Nothing": "Rien",
    "Nothing to export": "Rien à exporter",
    "Nothing to flash: select a firmware or enable the filesystem": "Rien à flasher : sélectionnez un firmware ou activez le système de fichiers",
    "Nothing to import in this file": "Rien à importer dans ce fichier",
    "Nothing to save": "Rien à enregistrer",
    "Nothing to send": "Rien à envoyer",
    "Notification": "Notification",
    "Notifications": "Notifications",
    "Notify": "Notifier",
    "Notify when a port is lost": "Notifier quand un port est perdu",
    "Notify when flash jobs finish": "Notifier à la fin des tâches de flash",
    "Numbers (CSV / spaces)": "Nombres (CSV / espaces)",
    "Numeric series (plottable)": "Séries numériques (traçables)",
    "OTA data partition (boot the factory app again)": "Partition de données OTA (redémarrer sur l'application d'usine)",
    "Odd": "Impaire",
    "Offset": "Offset",
    "Offset (ESP .bin only)": "Offset (.bin ESP uniquement)",
    "On timeout": "En cas de délai dépassé",
    "One package index URL per line, same format as the Arduino IDE": "Une URL d'index de paquets par ligne, même format que l'IDE Arduino",
    "One per send": "Une par envoi",
    "Open": "Ouvrir",
    "Open .dtcap files with File > Open capture, then compare the two tabs": "Ouvrez les fichiers .dtcap via Fichier > Ouvrir une capture, puis comparez les deux onglets",
    "Open a port first": "Ouvrez d'abord un port",
    "Open a serial port first": "Ouvrez d'abord un port série",
    "Open and connect": "Ouvrir et connecter",
    "Open board manager": "Ouvrir le gestionnaire de cartes",
    "Open capture": "Ouvrir une capture",
    "Open capture / replay": "Ouvrir une capture / rejouer",
    "Open data folder": "Ouvrir le dossier des données",
    "Open folder": "Ouvrir le dossier",
    "Open in a terminal: it will be released during flashing and reopened afterwards": "Ouvert dans un terminal : il sera libéré pendant le flash puis rouvert",
    "Open in terminal": "Ouvrir dans un terminal",
    "Open log folder": "Ouvrir le dossier des logs",
    "Open packages folder": "Ouvrir le dossier des paquets",
    "Open port in new tab": "Ouvrir le port dans un nouvel onglet",
    "Open sniffer tab": "Ouvrir l'onglet sniffer",
    "Open tabs": "Ouvrir les onglets",
    "Open the port before sending a file": "Ouvrez le port avant d'envoyer un fichier",
    "Opening...": "Ouverture...",
    "Operation": "Opération",
    "Operations use the board and options selected in the Flash tab": "Les opérations utilisent la carte et les options choisies dans l'onglet Flash",
    "Options": "Options",
    "Other": "Autre",
    "Overwrite": "Écraser",
    "Pack offsets": "Compacter les offsets",
    "Package": "Paquet",
    "Package not installed": "Paquet non installé",
    "Packages folder": "Dossier des paquets",
    "Parity": "Parité",
    "Parsers": "Analyseurs",
    "Partition": "Partition",
    "Partition editor": "Éditeur de partitions",
    "Partition layout": "Disposition des partitions",
    "Partition table": "Table de partitions",
    "Partition table editor": "Éditeur de table de partitions",
    "Partition table is valid": "La table de partitions est valide",
    "Partitions": "Partitions",
    "Pattern": "Motif",
    "Pause": "Pause",
    "Payload": "Contenu",
    "Place cursor A (Shift+click)": "Placer le curseur A (Maj+clic)",
    "Place cursor B (Alt+click)": "Placer le curseur B (Alt+clic)",
    "Play": "Lecture",
    "Play sounds": "Jouer des sons",
    "Plot": "Tracer",
    "Plotter": "Traceur",
    "Points kept per series": "Points conservés par série",
    "Port": "Port",
    "Port A (device side)": "Port A (côté appareil)",
    "Port B (host side)": "Port B (côté hôte)",
    "Port detection interval": "Intervalle de détection des ports",
    "Port lost": "Port perdu",
    "Port name": "Nom du port",
    "Port not open": "Port non ouvert",
    "Port reconnected": "Port reconnecté",
    "Port suspended (in use by flash job)": "Port suspendu (utilisé par une tâche de flash)",
    "Ports": "Ports",
    "Prebuilt image file": "Fichier image préconstruit",
    "Press a key (F1-F12, Ctrl+...)": "Appuyez sur une touche (F1-F12, Ctrl+...)",
    "Press keys...": "Appuyez sur les touches...",
    "Prevents flashing the same board twice when it re-enumerates after reset": "Évite de flasher deux fois la même carte quand elle se ré-énumère après un reset",
    "Preview": "Aperçu",
    "Previous match": "Occurrence précédente",
    "Previous match (Shift+Enter)": "Occurrence précédente (Maj+Entrée)",
    "Previous tab": "Onglet précédent",
    "Printable": "Imprimables",
    "Production mode": "Mode production",
    "Production mode USB filters": "Filtres USB du mode production",
    "Production mode: ignore a board for": "Mode production : ignorer une carte pendant",
    "Profile": "Profil",
    "Profile \"{name}\" saved": "Profil \"{name}\" enregistré",
    "Profile name": "Nom du profil",
    "Program": "Programmer",
    "Programmer": "Programmateur",
    "Project": "Projet",
    "Protocol": "Protocole",
    "Protocol decoder": "Décodeur de protocole",
    "Protocol decoding": "Décodage de protocole",
    "Pulse reset (DTR/RTS)": "Impulsion de reset (DTR/RTS)",
    "Put in send box": "Mettre dans la zone d'envoi",
    "Queue": "File d'attente",
    "Queued": "En attente",
    "Quit": "Quitter",
    "Quit DiagTerm? {details}": "Quitter DiagTerm ? {details}",
    "RTS on open": "RTS à l'ouverture",
    "RX color": "Couleur RX",
    "RX text color": "Couleur du texte RX",
    "RX/TX timeline": "Timeline RX/TX",
    "Random integer": "Entier aléatoire",
    "Raw (whole file, as fast as possible)": "Brut (fichier entier, au plus vite)",
    "Raw RX bytes": "Octets RX bruts",
    "Raw USB chunks": "Blocs USB bruts",
    "Raw binary (.bin)": "Binaire brut (.bin)",
    "Raw bytes of the selected directions are concatenated in time order.": "Les octets bruts des directions sélectionnées sont concaténés dans l'ordre chronologique.",
    "Read flash": "Lire la flash",
    "Read from device": "Lire depuis l'appareil",
    "Read from device (ESP32)": "Lire depuis l'appareil (ESP32)",
    "Read from {port}": "Lire depuis {port}",
    "Read info": "Lire les infos",
    "Read partition table": "Lire la table de partitions",
    "Read partitions": "Lire les partitions",
    "Read to file": "Lire vers un fichier",
    "Reading chip info": "Lecture des infos de la puce",
    "Reading filesystem": "Lecture du système de fichiers",
    "Reading filesystem...": "Lecture du système de fichiers...",
    "Reading flash": "Lecture de la flash",
    "Reading partition table": "Lecture de la table de partitions",
    "Reading partition table from {port}...": "Lecture de la table de partitions depuis {port}...",
    "Reading the layout from the device requires a port": "Lire la disposition depuis l'appareil nécessite un port",
    "Reads the filesystem partition and extracts every file (ESP32 and ESP8266). Uses the first selected port.": "Lit la partition du système de fichiers et en extrait tous les fichiers (ESP32 et ESP8266). Utilise le premier port sélectionné.",
    "Reads the partition table of an ESP32 and opens it in the partition editor.": "Lit la table de partitions d'un ESP32 et l'ouvre dans l'éditeur de partitions.",
    "Reboot via 1200 bps touch": "Redémarrage par touch 1200 bps",
    "Rec": "Rec",
    "Receive / transmit rate": "Débit de réception / émission",
    "Recent": "Récentes",
    "Recompute offsets sequentially with the required alignment": "Recalculer les offsets à la suite avec l'alignement requis",
    "Reconnect abandoned": "Reconnexion abandonnée",
    "Reconnected": "Reconnecté",
    "Reconnecting": "Reconnexion",
    "Reconnecting ({n})": "Reconnexion ({n})",
    "Reconnection": "Reconnexion",
    "Reconnection abandoned after {n} attempts": "Reconnexion abandonnée après {n} tentatives",
    "Reconnections": "Reconnexions",
    "Record every port to disk": "Enregistrer chaque port sur disque",
    "Record to disk": "Enregistrer sur disque",
    "Recorded": "Enregistré",
    "Recording {n}": "Enregistrement {n}",
    "Refresh": "Actualiser",
    "Refresh ports": "Actualiser les ports",
    "Regex": "Regex",
    "Regex groups": "Groupes regex",
    "Regex with groups, e.g. T=(?<temp>[\\d.]+)": "Regex avec groupes, ex. T=(?<temp>[\\d.]+)",
    "Regular expression": "Expression régulière",
    "Release notes": "Notes de version",
    "Reload": "Recharger",
    "Reload interface": "Recharger l'interface",
    "Reload the interface now to apply this change? Open ports stay connected.": "Recharger l'interface maintenant pour appliquer ce changement ? Les ports ouverts restent connectés.",
    "Reload the interface to apply every imported value?": "Recharger l'interface pour appliquer toutes les valeurs importées ?",
    "Remember sent commands between sessions": "Mémoriser les commandes envoyées entre les sessions",
    "Remove": "Supprimer",
    "Remove {key} {v}?": "Supprimer {key} {v} ?",
    "Remove {v}": "Supprimer {v}",
    "Removes NVS, Wi-Fi credentials and filesystem": "Supprime la NVS, les identifiants Wi-Fi et le système de fichiers",
    "Rename": "Renommer",
    "Rename tab": "Renommer l'onglet",
    "Rename tab...": "Renommer l'onglet...",
    "Rename workspace": "Renommer l'espace de travail",
    "Rename...": "Renommer...",
    "Reopen the terminal port after flashing": "Rouvrir le port du terminal après le flash",
    "Repeat": "Répéter",
    "Repeat every (ms)": "Répéter toutes les (ms)",
    "Replay": "Rejeu",
    "Replay in real time": "Rejouer en temps réel",
    "Reply ($1 = regex group)": "Réponse ($1 = groupe regex)",
    "Report CSV": "Rapport CSV",
    "Report saved": "Rapport enregistré",
    "Reset": "Reset",
    "Reset \"{name}\" to default values?": "Réinitialiser \"{name}\" aux valeurs par défaut ?",
    "Reset all": "Tout réinitialiser",
    "Reset all shortcuts": "Réinitialiser tous les raccourcis",
    "Reset board (DTR/RTS pulse)": "Reset de la carte (impulsion DTR/RTS)",
    "Reset chronometer": "Remettre le chronomètre à zéro",
    "Reset every setting to its default value? Macros, triggers and workspaces are kept.": "Réinitialiser tous les réglages à leur valeur par défaut ? Les macros, déclencheurs et espaces de travail sont conservés.",
    "Reset this section": "Réinitialiser cette section",
    "Reset to default": "Valeur par défaut",
    "Response time (TX end to next RX start)": "Temps de réponse (fin TX jusqu'au début RX suivant)",
    "Response time (after TX)": "Temps de réponse (après TX)",
    "Restore": "Restaurer",
    "Restore every default shortcut?": "Restaurer tous les raccourcis par défaut ?",
    "Restore tabs and reopen ports on startup": "Restaurer les onglets et rouvrir les ports au démarrage",
    "Results": "Résultats",
    "Results copied": "Résultats copiés",
    "Results of the operations started here appear in this table.": "Les résultats des opérations lancées ici apparaissent dans ce tableau.",
    "Resume": "Reprendre",
    "Retries": "Tentatives",
    "Retries per step": "Tentatives par étape",
    "Retry": "Réessayer",
    "Retry failed": "Relancer les échecs",
    "Retry interval": "Intervalle entre tentatives",
    "Run macro": "Lancer une macro",
    "Run on active tab": "Exécuter sur l'onglet actif",
    "Running": "En cours",
    "Running and queued": "En cours et en attente",
    "Runs the exact upload command defined by the board package, like the Arduino IDE": "Exécute la commande d'envoi exacte définie par le paquet de la carte, comme l'IDE Arduino",
    "SLIP framed": "Tramé SLIP",
    "Same rules as RX": "Mêmes règles que RX",
    "Same type": "Même type",
    "Sample frame text": "Exemple de texte de trame",
    "Save": "Enregistrer",
    "Save as macro...": "Enregistrer comme macro...",
    "Save as...": "Enregistrer sous...",
    "Save capture (.dtcap)": "Enregistrer la capture (.dtcap)",
    "Save capture snapshot": "Enregistrer un instantané de la capture",
    "Save current as...": "Enregistrer l'actuel sous...",
    "Save flash profile": "Enregistrer le profil de flash",
    "Save the send box as a macro": "Enregistrer la zone d'envoi comme macro",
    "Save workspace": "Enregistrer l'espace de travail",
    "Save workspace as...": "Enregistrer l'espace de travail sous...",
    "Scale": "Échelle",
    "Scope": "Portée",
    "Scrollable RX/TX timeline with UART logic analyzer view": "Timeline RX/TX défilante avec vue analyseur logique UART",
    "Search by name, FQBN, MCU or platform": "Rechercher par nom, FQBN, MCU ou plateforme",
    "Search commands, tabs, ports...": "Rechercher des commandes, onglets, ports...",
    "Search in logs": "Rechercher dans les logs",
    "Search in logs...": "Rechercher dans les logs...",
    "Search packages and boards": "Rechercher des paquets et des cartes",
    "Search settings": "Rechercher un réglage",
    "Searching for COMNEX devices...": "Recherche d'appareils COMNEX...",
    "Seconds since start": "Secondes depuis le début",
    "Select a board": "Sélectionner une carte",
    "Select a board first": "Sélectionnez d'abord une carte",
    "Select a board to see the filesystem area": "Sélectionnez une carte pour voir la zone du système de fichiers",
    "Select a board...": "Sélectionner une carte...",
    "Select a file first": "Sélectionnez d'abord un fichier",
    "Select a file to see how it will be split.": "Sélectionnez un fichier pour voir comment il sera découpé.",
    "Select a firmware, a filesystem or enable erase": "Sélectionnez un firmware, un système de fichiers ou activez l'effacement",
    "Select a job to see its log": "Sélectionnez une tâche pour voir son log",
    "Select a port": "Sélectionner un port",
    "Select a port first": "Sélectionnez d'abord un port",
    "Select a programmer": "Sélectionner un programmateur",
    "Select an ESP32 board and a port": "Sélectionnez une carte ESP32 et un port",
    "Select at least one port": "Sélectionnez au moins un port",
    "Select every port with the same VID:PID as the selection": "Sélectionner tous les ports ayant le même VID:PID que la sélection",
    "Select or add an item.": "Sélectionnez ou ajoutez un élément.",
    "Select port...": "Sélectionner un port...",
    "Select ports not opened in a terminal": "Sélectionner les ports non ouverts dans un terminal",
    "Select the filesystem source": "Sélectionnez la source du système de fichiers",
    "Select the source folder": "Sélectionnez le dossier source",
    "Selected frames ({n})": "Trames sélectionnées ({n})",
    "Send": "Envoyer",
    "Send a file": "Envoyer un fichier",
    "Send again": "Renvoyer",
    "Send break": "Envoyer un break",
    "Send file": "Envoyer un fichier",
    "Send file to {port}": "Envoyer un fichier vers {port}",
    "Send history size": "Taille de l'historique d'envoi",
    "Send periodically": "Envoyer périodiquement",
    "Sending {file} ({size})": "Envoi de {file} ({size})",
    "Sequence (optional, replaces the payload above)": "Séquence (optionnelle, remplace le contenu ci-dessus)",
    "Serial and framing options": "Options série et de découpage",
    "Serial defaults": "Valeurs série par défaut",
    "Serial plotter": "Traceur série",
    "Serial plotter and protocol decoders (Modbus, NMEA, SLIP, COBS, custom)": "Traceur série et décodeurs de protocoles (Modbus, NMEA, SLIP, COBS, personnalisés)",
    "Serial port": "Port série",
    "Serial prefix": "Préfixe du numéro de série",
    "Serial terminal, protocol analyzer and multi-board flasher": "Terminal série, analyseur de protocoles et flasheur multi-cartes",
    "Settings": "Réglages",
    "Shift": "Maj",
    "Shortcut": "Raccourci",
    "Show control characters": "Afficher les caractères de contrôle",
    "Show control characters (CR, LF...)": "Afficher les caractères de contrôle (CR, LF...)",
    "Show direction column (RX/TX)": "Afficher la colonne de direction (RX/TX)",
    "Show flash": "Afficher le flash",
    "Show in macro bar": "Afficher dans la barre de macros",
    "Show in pane {n}": "Afficher dans le volet {n}",
    "Show in timeline": "Afficher dans la timeline",
    "Show laps": "Afficher les tours",
    "Show matching frames only": "Afficher uniquement les trames correspondantes",
    "Show minimap": "Afficher la minicarte",
    "Show settings": "Afficher les réglages",
    "Show terminals": "Afficher les terminaux",
    "Show timeline in new tabs": "Afficher la timeline dans les nouveaux onglets",
    "Show transmitted data": "Afficher les données émises",
    "Signature": "Signature",
    "Silence (ms)": "Silence (ms)",
    "Silence timeout": "Délai de silence",
    "Since connection": "Depuis la connexion",
    "Since last RX": "Depuis le dernier RX",
    "Since previous frame": "Depuis la trame précédente",
    "Since start": "Depuis le début",
    "Single file": "Fichier unique",
    "Single view": "Vue simple",
    "Size": "Taille",
    "Skip empty lines": "Ignorer les lignes vides",
    "Snapshot capture to log folder": "Instantané de la capture dans le dossier des logs",
    "Snapshot saved: {file}": "Instantané enregistré : {file}",
    "Sniffer": "Sniffer",
    "Sniffer: RX = {a} to {b}, TX = {b} to {a}": "Sniffer : RX = {a} vers {b}, TX = {b} vers {a}",
    "Software (XON/XOFF)": "Logiciel (XON/XOFF)",
    "Sound": "Son",
    "Sound volume": "Volume sonore",
    "Source": "Source",
    "Space": "Space",
    "Split": "Partager",
    "Split horizontally": "Partager horizontalement",
    "Split vertically": "Partager verticalement",
    "Standalone board manager and bulk flashing without the Arduino IDE": "Gestionnaire de cartes autonome et flash en masse sans l'IDE Arduino",
    "Start": "Démarrer",
    "Start a new file after": "Nouveau fichier après",
    "Start a new file every": "Nouveau fichier toutes les",
    "Start bridge": "Démarrer le pont",
    "Start chronometer": "Démarrer le chronomètre",
    "Start chronometer here": "Démarrer le chronomètre ici",
    "Start production mode? Every matching board plugged in will be flashed with \"{name}\".": "Démarrer le mode production ? Chaque carte correspondante branchée sera flashée avec \"{name}\".",
    "Start to start: {a} - End to start: {b}": "Début à début : {a} - Fin à début : {b}",
    "Starts with": "Commence par",
    "Statistics": "Statistiques",
    "Statistics - {name}": "Statistiques - {name}",
    "Statistics...": "Statistiques...",
    "Status": "État",
    "Steps": "Étapes",
    "Stop": "Arrêter",
    "Stop bits": "Bits de stop",
    "Stop chronometer": "Arrêter le chronomètre",
    "Stop chronometer here": "Arrêter le chronomètre ici",
    "Subtype": "Sous-type",
    "Succeeded": "Réussi",
    "Sum (8-bit)": "Somme (8 bits)",
    "Sum (two's complement)": "Somme (complément à deux)",
    "Sync": "Synchro",
    "Sync bytes (hex)": "Octets de synchro (hexa)",
    "Synchronize timelines across panes": "Synchroniser les timelines entre les volets",
    "Synchronize timelines across split panes": "Synchroniser les timelines entre les volets partagés",
    "System and markers": "Système et marqueurs",
    "TCP client (connect to host)": "Client TCP (connexion à un hôte)",
    "TCP port": "Port TCP",
    "TCP server (raw socket)": "Serveur TCP (socket brut)",
    "TX color": "Couleur TX",
    "TX frames": "Trames TX",
    "TX text color": "Couleur du texte TX",
    "Tab delimited (.txt)": "Délimité par tabulations (.txt)",
    "Tab title (empty for port name)": "Titre de l'onglet (vide pour le nom du port)",
    "Tabs": "Onglets",
    "Target ports": "Ports cibles",
    "Telnet server": "Serveur Telnet",
    "Terminal": "Terminal",
    "Test": "Test",
    "Test sound": "Tester le son",
    "Test with a sample frame": "Tester avec une trame d'exemple",
    "Text": "Texte",
    "Text (UTF-8)": "Texte (UTF-8)",
    "Text and hex": "Texte et hexa",
    "Text color": "Couleur du texte",
    "Text encoding": "Encodage du texte",
    "Text log (.txt)": "Log texte (.txt)",
    "Text with timestamps": "Texte avec horodatage",
    "Text, hex and mixed views, timestamps, search, highlights and filters": "Vues texte, hexa et mixte, horodatage, recherche, surlignages et filtres",
    "The partition table is read from each board before writing": "La table de partitions est lue sur chaque carte avant l'écriture",
    "The update requires a manual installation (self-signed certificate). The download has been opened in your browser.": "La mise à jour nécessite une installation manuelle (certificat auto-signé). Le téléchargement a été ouvert dans votre navigateur.",
    "Theme": "Thème",
    "Time": "Heure",
    "Timeline": "Timeline",
    "Timeline cursor A here": "Curseur A de la timeline ici",
    "Timeline cursor B here": "Curseur B de la timeline ici",
    "Timeline marker": "Marqueur dans la timeline",
    "Timeout": "Délai",
    "Timeout (ms)": "Délai (ms)",
    "Timestamp mode": "Mode d'horodatage",
    "Timestamps: {mode}": "Horodatage : {mode}",
    "Timing": "Temporisation",
    "Timing is reconstructed from host timestamps: each USB chunk is spread at line rate (baud, data bits, parity, stop bits). Gaps inside a chunk are not observable, inter-chunk gaps are accurate to the USB latency (typically 1-16 ms).": "La temporisation est reconstruite à partir de l'horodatage de l'hôte : chaque bloc USB est étalé au débit de la ligne (bauds, bits de données, parité, bits de stop). Les écarts à l'intérieur d'un bloc ne sont pas observables, les écarts entre blocs sont précis à la latence USB près (en général 1 à 16 ms).",
    "Toggle": "Basculer",
    "Toggle auto-scroll": "Activer / désactiver le défilement auto",
    "Toggle automatic reconnection": "Activer / désactiver la reconnexion automatique",
    "Toggle control characters": "Afficher / masquer les caractères de contrôle",
    "Toggle decoder": "Afficher / masquer le décodeur",
    "Toggle developer tools": "Afficher / masquer les outils de développement",
    "Toggle disk recording": "Activer / désactiver l'enregistrement sur disque",
    "Toggle light / dark theme": "Basculer thème clair / sombre",
    "Toggle line wrap": "Activer / désactiver le retour à la ligne",
    "Toggle plotter": "Afficher / masquer le traceur",
    "Toggle timeline": "Afficher / masquer la timeline",
    "Toggle timeline synchronization": "Activer / désactiver la synchronisation des timelines",
    "Tool": "Outil",
    "Tools": "Outils",
    "Total": "Total",
    "Total received / sent": "Total reçu / envoyé",
    "Trigger": "Déclencheur",
    "Triggers and alerts": "Déclencheurs et alertes",
    "Triggers and alerts...": "Déclencheurs et alertes...",
    "Type": "Type",
    "Type a command, a tab, a macro or a port...": "Tapez une commande, un onglet, une macro ou un port...",
    "Type a message... (Enter to send, Up/Down for history)": "Tapez un message... (Entrée pour envoyer, Haut/Bas pour l'historique)",
    "URLs and options": "URL et options",
    "Unable to read file": "Impossible de lire le fichier",
    "Unit": "Unité",
    "Unknown error": "Erreur inconnue",
    "Unsaved configuration": "Configuration non enregistrée",
    "Until next frame": "Jusqu'à la trame suivante",
    "Untitled": "Sans titre",
    "Up": "Monter",
    "Update": "Mettre à jour",
    "Update all": "Tout mettre à jour",
    "Update check interval": "Intervalle de vérification des mises à jour",
    "Update error: {error}": "Erreur de mise à jour : {error}",
    "Update indexes": "Mettre à jour les index",
    "Update {version} downloaded. Restart DiagTerm to install it.": "Mise à jour {version} téléchargée. Redémarrez DiagTerm pour l'installer.",
    "Updates": "Mises à jour",
    "Updates available": "Mises à jour disponibles",
    "Upload a filesystem with the firmware": "Envoyer un système de fichiers avec le firmware",
    "Upload filesystem": "Envoyer le système de fichiers",
    "Upload method": "Méthode d'envoi",
    "Upload speed": "Vitesse d'envoi",
    "Upload speed override": "Forcer la vitesse d'envoi",
    "Upload to boards": "Envoyer vers les cartes",
    "Uploading filesystem": "Envoi du système de fichiers",
    "Uploading firmware": "Envoi du firmware",
    "Use the platform upload recipe (generic driver)": "Utiliser la recette d'envoi de la plateforme (pilote générique)",
    "Value inspector": "Inspecteur de valeurs",
    "Variables": "Variables",
    "Variables: {port} {date} {time} {datetime}": "Variables : {port} {date} {time} {datetime}",
    "Verbose tool output": "Sortie détaillée des outils",
    "Verify": "Vérifier",
    "Verify after upload": "Vérifier après l'envoi",
    "Verify after writing": "Vérifier après l'écriture",
    "Verifying": "Vérification",
    "Version {version}": "Version {version}",
    "View": "Affichage",
    "View as hex": "Afficher en hexa",
    "View as hex dump": "Afficher en dump hexa",
    "View as text": "Afficher en texte",
    "Visible window": "Fenêtre visible",
    "Wait for RX": "Attendre RX",
    "Wait for acknowledge after each frame": "Attendre un acquittement après chaque trame",
    "Waiting for data...": "En attente de données...",
    "Waiting for numeric data...": "En attente de données numériques...",
    "WebSocket frames": "Trames WebSocket",
    "WebSocket server": "Serveur WebSocket",
    "Whitespace": "Espaces",
    "Whole capture": "Capture entière",
    "Whole line": "Ligne entière",
    "Window": "Fenêtre",
    "Workspace": "Espace de travail",
    "Workspace \"{name}\" loaded": "Espace de travail \"{name}\" chargé",
    "Workspace \"{name}\" saved": "Espace de travail \"{name}\" enregistré",
    "Workspace name": "Nom de l'espace de travail",
    "Workspaces": "Espaces de travail",
    "Wrap long lines": "Retour à la ligne automatique",
    "Write": "Écrire",
    "Write failed: {error}": "Échec de l'écriture : {error}",
    "Write partitions": "Écrire les partitions",
    "Write this partition table to {port}? Data in moved partitions will be lost and the firmware may need to be reflashed.": "Écrire cette table de partitions sur {port} ? Les données des partitions déplacées seront perdues et le firmware devra peut-être être reflashé.",
    "Write to device...": "Écrire sur l'appareil...",
    "Writes the bootloader and fuses with a programmer (AVR ISP, USBasp, Arduino as ISP...).": "Écrit le bootloader et les fusibles avec un programmateur (AVR ISP, USBasp, Arduino as ISP...).",
    "Writing partition table": "Écriture de la table de partitions",
    "XML/HTML-like": "Type XML/HTML",
    "XOR of preceding bytes": "XOR des octets précédents",
    "Zero-terminated (COBS / C string)": "Terminé par zéro (COBS / chaîne C)",
    "Zoom in": "Zoom avant",
    "Zoom out": "Zoom arrière",
    "Zoom to selected frame": "Zoomer sur la trame sélectionnée",
    "absent": "absent",
    "advanced": "avancé",
    "at": "à",
    "at offset": "à l'offset",
    "avg": "moy.",
    "before line ending": "avant la fin de ligne",
    "bits/byte": "bits/octet",
    "busy": "occupé",
    "by {m}": "par {m}",
    "cancelled": "annulé",
    "chunks": "blocs",
    "client": "client",
    "client(s)": "client(s)",
    "computed from byte": "calculé depuis l'octet",
    "deprecated": "obsolète",
    "detected": "détecté",
    "detected on {port}": "détectée sur {port}",
    "differences": "différences",
    "erase": "effacement",
    "extra in capture": "en plus dans la capture",
    "failed": "échoué",
    "fields": "champs",
    "filters": "filtres",
    "firmware": "firmware",
    "font": "police",
    "frame": "trame",
    "frames": "trames",
    "gap": "écart",
    "highlights": "surlignages",
    "hits": "résultats",
    "host": "hôte",
    "identical": "identiques",
    "in": "entrée",
    "in terminal": "dans un terminal",
    "invalid": "invalide",
    "key:value pairs": "paires clé:valeur",
    "key:value pairs (plottable)": "paires clé:valeur (traçables)",
    "logic": "logique",
    "match": "correspondance",
    "missing from capture": "absentes de la capture",
    "more": "de plus",
    "n random bytes as hex": "n octets aléatoires en hexa",
    "optional": "optionnel",
    "optional, e.g. AA 55": "optionnel, ex. AA 55",
    "out": "sortie",
    "pairs": "paires",
    "pass": "passe",
    "peak": "pic",
    "playing": "lecture",
    "production": "production",
    "queued": "en attente",
    "recent": "récent",
    "running": "en cours",
    "server": "serveur",
    "settings": "réglages",
    "size": "taille",
    "skip {n}": "ignorer {n}",
    "sniffer": "sniffer",
    "succeeded": "réussi",
    "text": "texte",
    "theme": "thème",
    "total = value +": "total = valeur +",
    "total since open": "total depuis l'ouverture",
    "triggers": "déclencheurs",
    "verify": "vérification",
    "website": "site web",
    "whole line": "ligne entière",
    "{key} {v} installed": "{key} {v} installé",
    "{list} already have a running job. Queue anyway?": "{list} ont déjà une tâche en cours. Mettre en file quand même ?",
    "{n} attempts": "{n} tentatives",
    "{n} bridges": "{n} ponts",
    "{n} errors": "{n} erreurs",
    "{n} files": "{n} fichiers",
    "{n} files extracted to {dir}": "{n} fichiers extraits dans {dir}",
    "{n} flash jobs in progress": "{n} tâches de flash en cours",
    "{n} frames": "{n} trames",
    "{n} frames, {ok} valid, {bad} invalid": "{n} trames, {ok} valides, {bad} invalides",
    "{n} open ports ({list})": "{n} ports ouverts ({list})",
    "{n} packages installed": "{n} paquets installés",
    "{n} partitions": "{n} partitions",
    "{n} profiles imported": "{n} profils importés",
    "{n} reconnections": "{n} reconnexions",
    "{n} results": "{n} résultats",
    "{n} steps": "{n} étapes",
    "{n} tabs": "{n} onglets",
    "{n} updates available": "{n} mises à jour disponibles",
    "{old} is back as {port}": "{old} est revenu en tant que {port}",
    "{port} disconnected": "{port} déconnecté",
    "{port} is open in a tab. Close it first.": "{port} est ouvert dans un onglet. Fermez-le d'abord.",
    "{port} not present: waiting for the device": "{port} absent : en attente de l'appareil",
    "{port} reconnected": "{port} reconnecté",
    "{proto}: {n} blocks of {b} bytes. Start the receiver first; the transfer begins when it requests data.": "{proto} : {n} blocs de {b} octets. Démarrez d'abord le récepteur ; le transfert commence quand il demande des données.",
    "{size} in {n} frame(s)": "{size} en {n} trame(s)",
    "{used} used of {total}, {free} free": "{used} utilisés sur {total}, {free} libres",
    "{v} available": "{v} disponible"
};
